/********************************************************************************
** Form generated from reading UI file 'siviso.ui'
**
** Created by: Qt User Interface Compiler version 5.2.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_SIVISO_H
#define UI_SIVISO_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDial>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_SIVISO
{
public:
    QWidget *centralWidget;
    QFrame *frame;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QFrame *frame_2;
    QSlider *horizontalSlider;
    QLabel *label_7;
    QFrame *frame_9;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QFrame *frame_10;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QLabel *label_19;
    QDoubleSpinBox *doubleSpinBox;
    QLabel *label_8;
    QDoubleSpinBox *doubleSpinBox_3;
    QDoubleSpinBox *doubleSpinBox_4;
    QLabel *label_11;
    QLabel *label_12;
    QFrame *frame_11;
    QPushButton *pushButton_9;
    QDoubleSpinBox *doubleSpinBox_5;
    QDoubleSpinBox *doubleSpinBox_6;
    QDoubleSpinBox *doubleSpinBox_7;
    QDoubleSpinBox *doubleSpinBox_8;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QPushButton *pushButton_10;
    QLabel *label_18;
    QGroupBox *groupBox;
    QRadioButton *radioButton;
    QRadioButton *radioButton_2;
    QRadioButton *radioButton_3;
    QFrame *frame_14;
    QLabel *label_20;
    QPushButton *pushButton_11;
    QComboBox *comboBox;
    QSpinBox *spinBox;
    QLabel *label_21;
    QDoubleSpinBox *doubleSpinBox_9;
    QLabel *label_22;
    QDoubleSpinBox *doubleSpinBox_10;
    QLabel *label_23;
    QLabel *label_24;
    QDoubleSpinBox *doubleSpinBox_11;
    QLabel *label_25;
    QDoubleSpinBox *doubleSpinBox_12;
    QLabel *label_26;
    QDoubleSpinBox *doubleSpinBox_13;
    QDial *dial;
    QGroupBox *groupBox_2;
    QRadioButton *radioButton_4;
    QRadioButton *radioButton_5;
    QRadioButton *radioButton_6;
    QPushButton *pushButton_12;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QFrame *frame_3;
    QLabel *label_27;
    QFrame *frame_4;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QFrame *frame_5;
    QFrame *frame_6;
    QFrame *frame_7;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QFrame *frame_8;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLabel *label_55;
    QLabel *label_56;
    QLabel *label_57;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *SIVISO)
    {
        if (SIVISO->objectName().isEmpty())
            SIVISO->setObjectName(QStringLiteral("SIVISO"));
        SIVISO->resize(1920, 1080);
        centralWidget = new QWidget(SIVISO);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        frame = new QFrame(centralWidget);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(10, 9, 1591, 71));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        label = new QLabel(frame);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 10, 67, 17));
        QFont font;
        font.setPointSize(8);
        font.setBold(false);
        font.setItalic(false);
        font.setWeight(50);
        label->setFont(font);
        label_2 = new QLabel(frame);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 40, 67, 17));
        label_2->setFont(font);
        label_2->setTextFormat(Qt::AutoText);
        label_3 = new QLabel(frame);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(150, 40, 111, 17));
        label_3->setFont(font);
        label_4 = new QLabel(frame);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(450, 40, 171, 17));
        label_4->setFont(font);
        label_5 = new QLabel(frame);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(890, 40, 201, 17));
        label_5->setFont(font);
        label_6 = new QLabel(frame);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(1270, 40, 191, 17));
        label_6->setFont(font);
        frame_2 = new QFrame(centralWidget);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(9, 89, 1591, 211));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        horizontalSlider = new QSlider(frame_2);
        horizontalSlider->setObjectName(QStringLiteral("horizontalSlider"));
        horizontalSlider->setGeometry(QRect(20, 40, 160, 29));
        horizontalSlider->setOrientation(Qt::Horizontal);
        label_7 = new QLabel(frame_2);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(60, 20, 91, 17));
        label_7->setFont(font);
        frame_9 = new QFrame(frame_2);
        frame_9->setObjectName(QStringLiteral("frame_9"));
        frame_9->setGeometry(QRect(10, 119, 131, 81));
        frame_9->setFrameShape(QFrame::StyledPanel);
        frame_9->setFrameShadow(QFrame::Raised);
        pushButton = new QPushButton(frame_9);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(10, 30, 51, 27));
        pushButton_2 = new QPushButton(frame_9);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(70, 30, 51, 27));
        frame_10 = new QFrame(frame_2);
        frame_10->setObjectName(QStringLiteral("frame_10"));
        frame_10->setGeometry(QRect(150, 120, 131, 81));
        frame_10->setFrameShape(QFrame::StyledPanel);
        frame_10->setFrameShadow(QFrame::Raised);
        pushButton_3 = new QPushButton(frame_10);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(10, 30, 51, 27));
        pushButton_4 = new QPushButton(frame_10);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(70, 30, 51, 27));
        label_19 = new QLabel(frame_10);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(30, 10, 67, 17));
        QFont font1;
        font1.setPointSize(8);
        font1.setBold(false);
        font1.setWeight(50);
        label_19->setFont(font1);
        doubleSpinBox = new QDoubleSpinBox(frame_2);
        doubleSpinBox->setObjectName(QStringLiteral("doubleSpinBox"));
        doubleSpinBox->setGeometry(QRect(200, 40, 91, 41));
        label_8 = new QLabel(frame_2);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(210, 10, 81, 17));
        label_8->setFont(font);
        doubleSpinBox_3 = new QDoubleSpinBox(frame_2);
        doubleSpinBox_3->setObjectName(QStringLiteral("doubleSpinBox_3"));
        doubleSpinBox_3->setGeometry(QRect(310, 40, 91, 41));
        doubleSpinBox_4 = new QDoubleSpinBox(frame_2);
        doubleSpinBox_4->setObjectName(QStringLiteral("doubleSpinBox_4"));
        doubleSpinBox_4->setGeometry(QRect(420, 40, 91, 41));
        label_11 = new QLabel(frame_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(290, 10, 121, 17));
        label_11->setFont(font);
        label_11->setAlignment(Qt::AlignCenter);
        label_12 = new QLabel(frame_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(420, 10, 91, 20));
        label_12->setFont(font);
        label_12->setAlignment(Qt::AlignCenter);
        frame_11 = new QFrame(frame_2);
        frame_11->setObjectName(QStringLiteral("frame_11"));
        frame_11->setGeometry(QRect(520, 10, 531, 91));
        frame_11->setFrameShape(QFrame::StyledPanel);
        frame_11->setFrameShadow(QFrame::Raised);
        pushButton_9 = new QPushButton(frame_11);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(10, 40, 81, 41));
        doubleSpinBox_5 = new QDoubleSpinBox(frame_11);
        doubleSpinBox_5->setObjectName(QStringLiteral("doubleSpinBox_5"));
        doubleSpinBox_5->setGeometry(QRect(100, 40, 91, 41));
        doubleSpinBox_6 = new QDoubleSpinBox(frame_11);
        doubleSpinBox_6->setObjectName(QStringLiteral("doubleSpinBox_6"));
        doubleSpinBox_6->setGeometry(QRect(210, 40, 91, 41));
        doubleSpinBox_7 = new QDoubleSpinBox(frame_11);
        doubleSpinBox_7->setObjectName(QStringLiteral("doubleSpinBox_7"));
        doubleSpinBox_7->setGeometry(QRect(320, 40, 91, 41));
        doubleSpinBox_8 = new QDoubleSpinBox(frame_11);
        doubleSpinBox_8->setObjectName(QStringLiteral("doubleSpinBox_8"));
        doubleSpinBox_8->setGeometry(QRect(430, 40, 91, 41));
        label_13 = new QLabel(frame_11);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 20, 91, 20));
        label_13->setFont(font);
        label_13->setAlignment(Qt::AlignCenter);
        label_14 = new QLabel(frame_11);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(100, 20, 91, 20));
        label_14->setFont(font);
        label_14->setAlignment(Qt::AlignCenter);
        label_15 = new QLabel(frame_11);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(210, 20, 91, 17));
        label_15->setFont(font);
        label_15->setAlignment(Qt::AlignCenter);
        label_16 = new QLabel(frame_11);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(320, 20, 91, 17));
        label_16->setFont(font);
        label_16->setAlignment(Qt::AlignCenter);
        label_17 = new QLabel(frame_11);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(430, 0, 91, 41));
        label_17->setFont(font);
        pushButton_10 = new QPushButton(frame_2);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(1080, 56, 99, 51));
        pushButton_10->setFocusPolicy(Qt::WheelFocus);
        label_18 = new QLabel(frame_2);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(1080, 20, 101, 41));
        groupBox = new QGroupBox(frame_2);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(1200, 9, 120, 101));
        radioButton = new QRadioButton(groupBox);
        radioButton->setObjectName(QStringLiteral("radioButton"));
        radioButton->setGeometry(QRect(10, 70, 81, 22));
        radioButton->setFont(font1);
        radioButton_2 = new QRadioButton(groupBox);
        radioButton_2->setObjectName(QStringLiteral("radioButton_2"));
        radioButton_2->setGeometry(QRect(10, 50, 81, 22));
        radioButton_2->setFont(font1);
        radioButton_3 = new QRadioButton(groupBox);
        radioButton_3->setObjectName(QStringLiteral("radioButton_3"));
        radioButton_3->setGeometry(QRect(10, 30, 81, 22));
        radioButton_3->setFont(font1);
        frame_14 = new QFrame(frame_2);
        frame_14->setObjectName(QStringLiteral("frame_14"));
        frame_14->setGeometry(QRect(290, 120, 221, 80));
        frame_14->setFrameShape(QFrame::StyledPanel);
        frame_14->setFrameShadow(QFrame::Raised);
        label_20 = new QLabel(frame_14);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(60, 10, 67, 17));
        pushButton_11 = new QPushButton(frame_14);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(10, 40, 99, 27));
        QFont font2;
        font2.setPointSize(8);
        pushButton_11->setFont(font2);
        comboBox = new QComboBox(frame_14);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(114, 40, 101, 27));
        comboBox->setFont(font2);
        spinBox = new QSpinBox(frame_2);
        spinBox->setObjectName(QStringLiteral("spinBox"));
        spinBox->setGeometry(QRect(540, 156, 48, 41));
        label_21 = new QLabel(frame_2);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(530, 120, 67, 31));
        doubleSpinBox_9 = new QDoubleSpinBox(frame_2);
        doubleSpinBox_9->setObjectName(QStringLiteral("doubleSpinBox_9"));
        doubleSpinBox_9->setGeometry(QRect(630, 160, 69, 41));
        label_22 = new QLabel(frame_2);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(616, 120, 91, 41));
        doubleSpinBox_10 = new QDoubleSpinBox(frame_2);
        doubleSpinBox_10->setObjectName(QStringLiteral("doubleSpinBox_10"));
        doubleSpinBox_10->setGeometry(QRect(734, 160, 69, 41));
        label_23 = new QLabel(frame_2);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(720, 120, 91, 41));
        label_24 = new QLabel(frame_2);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(826, 120, 91, 41));
        doubleSpinBox_11 = new QDoubleSpinBox(frame_2);
        doubleSpinBox_11->setObjectName(QStringLiteral("doubleSpinBox_11"));
        doubleSpinBox_11->setGeometry(QRect(840, 160, 69, 41));
        label_25 = new QLabel(frame_2);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(926, 116, 91, 41));
        doubleSpinBox_12 = new QDoubleSpinBox(frame_2);
        doubleSpinBox_12->setObjectName(QStringLiteral("doubleSpinBox_12"));
        doubleSpinBox_12->setGeometry(QRect(940, 160, 69, 41));
        label_26 = new QLabel(frame_2);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(1046, 126, 91, 31));
        doubleSpinBox_13 = new QDoubleSpinBox(frame_2);
        doubleSpinBox_13->setObjectName(QStringLiteral("doubleSpinBox_13"));
        doubleSpinBox_13->setGeometry(QRect(1060, 160, 69, 41));
        dial = new QDial(frame_2);
        dial->setObjectName(QStringLiteral("dial"));
        dial->setGeometry(QRect(1410, 0, 181, 211));
        groupBox_2 = new QGroupBox(frame_2);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(1290, 10, 120, 101));
        radioButton_4 = new QRadioButton(groupBox_2);
        radioButton_4->setObjectName(QStringLiteral("radioButton_4"));
        radioButton_4->setGeometry(QRect(10, 70, 81, 22));
        radioButton_4->setFont(font1);
        radioButton_5 = new QRadioButton(groupBox_2);
        radioButton_5->setObjectName(QStringLiteral("radioButton_5"));
        radioButton_5->setGeometry(QRect(10, 50, 101, 22));
        radioButton_5->setFont(font1);
        radioButton_6 = new QRadioButton(groupBox_2);
        radioButton_6->setObjectName(QStringLiteral("radioButton_6"));
        radioButton_6->setGeometry(QRect(10, 30, 121, 22));
        radioButton_6->setFont(font1);
        pushButton_12 = new QPushButton(frame_2);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(1230, 110, 61, 41));
        pushButton_13 = new QPushButton(frame_2);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(1300, 110, 61, 41));
        pushButton_14 = new QPushButton(frame_2);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(1230, 160, 61, 41));
        pushButton_15 = new QPushButton(frame_2);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(1300, 160, 61, 41));
        frame_3 = new QFrame(centralWidget);
        frame_3->setObjectName(QStringLiteral("frame_3"));
        frame_3->setGeometry(QRect(1609, 10, 301, 71));
        frame_3->setFrameShape(QFrame::StyledPanel);
        frame_3->setFrameShadow(QFrame::Raised);
        label_27 = new QLabel(frame_3);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(96, 10, 121, 51));
        frame_4 = new QFrame(centralWidget);
        frame_4->setObjectName(QStringLiteral("frame_4"));
        frame_4->setGeometry(QRect(1610, 90, 301, 351));
        frame_4->setFrameShape(QFrame::StyledPanel);
        frame_4->setFrameShadow(QFrame::Raised);
        label_28 = new QLabel(frame_4);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(110, 10, 101, 20));
        label_29 = new QLabel(frame_4);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 50, 67, 17));
        label_29->setFont(font2);
        label_30 = new QLabel(frame_4);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(20, 80, 71, 17));
        label_30->setFont(font2);
        label_31 = new QLabel(frame_4);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(20, 110, 67, 17));
        label_31->setFont(font2);
        label_32 = new QLabel(frame_4);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(20, 140, 67, 17));
        label_32->setFont(font2);
        label_33 = new QLabel(frame_4);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(20, 170, 111, 17));
        label_33->setFont(font2);
        label_34 = new QLabel(frame_4);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(20, 200, 67, 17));
        label_34->setFont(font2);
        label_35 = new QLabel(frame_4);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(20, 230, 67, 17));
        label_35->setFont(font2);
        label_36 = new QLabel(frame_4);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(20, 260, 91, 17));
        label_36->setFont(font2);
        label_37 = new QLabel(frame_4);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(20, 290, 101, 17));
        label_37->setFont(font2);
        label_38 = new QLabel(frame_4);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(170, 110, 67, 17));
        label_38->setFont(font2);
        label_39 = new QLabel(frame_4);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(170, 140, 67, 17));
        label_39->setFont(font2);
        frame_5 = new QFrame(centralWidget);
        frame_5->setObjectName(QStringLiteral("frame_5"));
        frame_5->setGeometry(QRect(10, 310, 791, 701));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Raised);
        frame_6 = new QFrame(centralWidget);
        frame_6->setObjectName(QStringLiteral("frame_6"));
        frame_6->setGeometry(QRect(810, 310, 791, 701));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Raised);
        frame_7 = new QFrame(centralWidget);
        frame_7->setObjectName(QStringLiteral("frame_7"));
        frame_7->setGeometry(QRect(1610, 450, 301, 241));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Raised);
        label_40 = new QLabel(frame_7);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(30, 200, 67, 17));
        label_40->setFont(font2);
        label_41 = new QLabel(frame_7);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(30, 80, 91, 17));
        label_41->setFont(font2);
        label_42 = new QLabel(frame_7);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(30, 170, 67, 17));
        label_42->setFont(font2);
        label_43 = new QLabel(frame_7);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(180, 170, 67, 17));
        label_43->setFont(font2);
        label_44 = new QLabel(frame_7);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(30, 50, 67, 17));
        label_44->setFont(font2);
        label_45 = new QLabel(frame_7);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(120, 10, 101, 20));
        label_46 = new QLabel(frame_7);
        label_46->setObjectName(QStringLiteral("label_46"));
        label_46->setGeometry(QRect(180, 200, 67, 17));
        label_46->setFont(font2);
        label_47 = new QLabel(frame_7);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(30, 110, 91, 17));
        label_47->setFont(font2);
        label_48 = new QLabel(frame_7);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(30, 140, 121, 17));
        label_48->setFont(font2);
        frame_8 = new QFrame(centralWidget);
        frame_8->setObjectName(QStringLiteral("frame_8"));
        frame_8->setGeometry(QRect(1610, 700, 301, 311));
        frame_8->setFrameShape(QFrame::StyledPanel);
        frame_8->setFrameShadow(QFrame::Raised);
        label_49 = new QLabel(frame_8);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(30, 210, 111, 17));
        label_49->setFont(font2);
        label_50 = new QLabel(frame_8);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(30, 150, 121, 17));
        label_50->setFont(font2);
        label_51 = new QLabel(frame_8);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(30, 90, 91, 17));
        label_51->setFont(font2);
        label_52 = new QLabel(frame_8);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(30, 270, 111, 17));
        label_52->setFont(font2);
        label_53 = new QLabel(frame_8);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(30, 120, 71, 17));
        label_53->setFont(font2);
        label_54 = new QLabel(frame_8);
        label_54->setObjectName(QStringLiteral("label_54"));
        label_54->setGeometry(QRect(30, 60, 101, 17));
        label_54->setFont(font2);
        label_55 = new QLabel(frame_8);
        label_55->setObjectName(QStringLiteral("label_55"));
        label_55->setGeometry(QRect(30, 180, 111, 17));
        label_55->setFont(font2);
        label_56 = new QLabel(frame_8);
        label_56->setObjectName(QStringLiteral("label_56"));
        label_56->setGeometry(QRect(120, 20, 101, 20));
        label_57 = new QLabel(frame_8);
        label_57->setObjectName(QStringLiteral("label_57"));
        label_57->setGeometry(QRect(30, 240, 101, 17));
        label_57->setFont(font2);
        SIVISO->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(SIVISO);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1920, 25));
        SIVISO->setMenuBar(menuBar);
        mainToolBar = new QToolBar(SIVISO);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        SIVISO->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(SIVISO);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        SIVISO->setStatusBar(statusBar);

        retranslateUi(SIVISO);

        QMetaObject::connectSlotsByName(SIVISO);
    } // setupUi

    void retranslateUi(QMainWindow *SIVISO)
    {
        SIVISO->setWindowTitle(QApplication::translate("SIVISO", "SIVISO", 0));
        label->setText(QApplication::translate("SIVISO", "Alertas", 0));
        label_2->setText(QApplication::translate("SIVISO", "id Alerta:", 0));
        label_3->setText(QApplication::translate("SIVISO", "Nombre Alerta:", 0));
        label_4->setText(QApplication::translate("SIVISO", "Parametro de la Alerta:", 0));
        label_5->setText(QApplication::translate("SIVISO", "Probabilidad de falsa alarma:", 0));
        label_6->setText(QApplication::translate("SIVISO", "Probabilidad de detecci\303\263n:", 0));
        label_7->setText(QApplication::translate("SIVISO", "Frecuiencia", 0));
        pushButton->setText(QApplication::translate("SIVISO", "Rec", 0));
        pushButton_2->setText(QApplication::translate("SIVISO", "Play", 0));
        pushButton_3->setText(QApplication::translate("SIVISO", "-", 0));
        pushButton_4->setText(QApplication::translate("SIVISO", "+", 0));
        label_19->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\">volumen</p></body></html>", 0));
        label_8->setText(QApplication::translate("SIVISO", "Bandwidth", 0));
        label_11->setText(QApplication::translate("SIVISO", "Integration time", 0));
        label_12->setText(QApplication::translate("SIVISO", "Display time", 0));
        pushButton_9->setText(QApplication::translate("SIVISO", "CW", 0));
        label_13->setText(QApplication::translate("SIVISO", "Enviar Pulso", 0));
        label_14->setText(QApplication::translate("SIVISO", "Frecuencia", 0));
        label_15->setText(QApplication::translate("SIVISO", "Potencia", 0));
        label_16->setText(QApplication::translate("SIVISO", "Tiempo", 0));
        label_17->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\">Rango de <br/>detecci\303\263n</p></body></html>", 0));
        pushButton_10->setText(QApplication::translate("SIVISO", "Norte \n"
"Verdadero", 0));
        label_18->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">altertar Norte<br/>Verdadero/Relativo </span></p></body></html>", 0));
        groupBox->setTitle(QApplication::translate("SIVISO", "Origen", 0));
        radioButton->setText(QApplication::translate("SIVISO", "Blanco", 0));
        radioButton_2->setText(QApplication::translate("SIVISO", "Sensor", 0));
        radioButton_3->setText(QApplication::translate("SIVISO", "Buque", 0));
        label_20->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Blancos</span></p></body></html>", 0));
        pushButton_11->setText(QApplication::translate("SIVISO", "Etiquetar blanco", 0));
        comboBox->clear();
        comboBox->insertItems(0, QStringList()
         << QApplication::translate("SIVISO", "Desconocido", 0)
         << QApplication::translate("SIVISO", "Amigo", 0)
         << QApplication::translate("SIVISO", "Neutral", 0)
         << QApplication::translate("SIVISO", "Enemigo", 0)
        );
        label_21->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Estado<br/>de la mar</span></p></body></html>", 0));
        label_22->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Probabilidad<br/>de falsa alarma</span></p></body></html>", 0));
        label_23->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Probabilidad<br/>de detecci\303\263n</span></p></body></html>", 0));
        label_24->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Escala<br/>PPI</span></p></body></html>", 0));
        label_25->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Escala<br/>despliegue<br/>t\303\241ctico</span></p></body></html>", 0));
        label_26->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Ganancia</span></p></body></html>", 0));
        groupBox_2->setTitle(QApplication::translate("SIVISO", "Origen", 0));
        radioButton_4->setText(QApplication::translate("SIVISO", "Manual", 0));
        radioButton_5->setText(QApplication::translate("SIVISO", "Automatico", 0));
        radioButton_6->setText(QApplication::translate("SIVISO", "Omnidireccional", 0));
        pushButton_12->setText(QApplication::translate("SIVISO", "Bb", 0));
        pushButton_13->setText(QApplication::translate("SIVISO", "Nb", 0));
        pushButton_14->setText(QApplication::translate("SIVISO", "BTR", 0));
        pushButton_15->setText(QApplication::translate("SIVISO", "PPI", 0));
        label_27->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">SIVISO</span></p><p align=\"center\"><span style=\" font-size:8pt;\">ARMADA DE M\303\211XICO</span></p></body></html>", 0));
        label_28->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Plataforma</span></p></body></html>", 0));
        label_29->setText(QApplication::translate("SIVISO", "Nombre:", 0));
        label_30->setText(QApplication::translate("SIVISO", "Profundidad:", 0));
        label_31->setText(QApplication::translate("SIVISO", "Latitud:", 0));
        label_32->setText(QApplication::translate("SIVISO", "COG:", 0));
        label_33->setText(QApplication::translate("SIVISO", "Orientaci\303\263n relativa:", 0));
        label_34->setText(QApplication::translate("SIVISO", "cable total:", 0));
        label_35->setText(QApplication::translate("SIVISO", "cable usado:", 0));
        label_36->setText(QApplication::translate("SIVISO", "cable disponible:", 0));
        label_37->setText(QApplication::translate("SIVISO", "temsion del cable:", 0));
        label_38->setText(QApplication::translate("SIVISO", "Longitud:", 0));
        label_39->setText(QApplication::translate("SIVISO", "SOG:", 0));
        label_40->setText(QApplication::translate("SIVISO", "COG:", 0));
        label_41->setText(QApplication::translate("SIVISO", "Etiqueta blanco:", 0));
        label_42->setText(QApplication::translate("SIVISO", "Latitud:", 0));
        label_43->setText(QApplication::translate("SIVISO", "Longitud:", 0));
        label_44->setText(QApplication::translate("SIVISO", "id blanco:", 0));
        label_45->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Blancos</span></p></body></html>", 0));
        label_46->setText(QApplication::translate("SIVISO", "SOG:", 0));
        label_47->setText(QApplication::translate("SIVISO", "Tipo blanco:", 0));
        label_48->setText(QApplication::translate("SIVISO", "Clasificaci\303\263n de blanco:", 0));
        label_49->setText(QApplication::translate("SIVISO", "Direcci\303\263n del viento:", 0));
        label_50->setText(QApplication::translate("SIVISO", "Profundidad del fondo:", 0));
        label_51->setText(QApplication::translate("SIVISO", "Estado del Mar:", 0));
        label_52->setText(QApplication::translate("SIVISO", "Velocidad del sonido:", 0));
        label_53->setText(QApplication::translate("SIVISO", "Tipo fondo:", 0));
        label_54->setText(QApplication::translate("SIVISO", "Salinidad del agua:", 0));
        label_55->setText(QApplication::translate("SIVISO", "Audio ambiente:", 0));
        label_56->setText(QApplication::translate("SIVISO", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">Medio ambiente</span></p></body></html>", 0));
        label_57->setText(QApplication::translate("SIVISO", "Fuerza del viento:", 0));
    } // retranslateUi

};

namespace Ui {
    class SIVISO: public Ui_SIVISO {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_SIVISO_H
